# stage environment (스테이지)

secrets:
  toss:
    apiUri: https://api.tosspayments.com/v1/payments/key-in

spring:
  application:
    name: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        auto_quote_keyword: true

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 40
      pool-name: mysqlM-example-cp
      hibernate:
        ddl-auto: validate
    slaves:
      - name: slave-1
        driver-class-name: com.mysql.cj.jdbc.Driver
        hibernate:
          ddl-auto: validate
      - name: slave-2
        driver-class-name: com.mysql.cj.jdbc.Driver
        hibernate:
          ddl-auto: validate

    postgres:
      driver-class-name: org.postgresql.Driver
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        pool-name: postgres-example-cp
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baselineOnMigrate: true
    cleanDisabled: true

  redis:
    host: localhost
    port: 6379

  cloud:
    vault:
      uri: http://3.35.52.88:8200
      token: ${VAULT_TOKEN}
      kv:
        backend: kv-v2
        default-context: application
  config:
    import: ${VAULT_IMPORT}

logging:
  level:
    org.hibernate.SQL: debug

origin:
  address: http://localhost:8080

jwt:
  key: applicationKey
  blackList: blackList
  expireTime:
    access: 3600000
    refresh: 1296000000

schedules:
  cron:
    product: "0 0 0 * * *"
    test: "1 * * * * *"